# SPDX-License-Identifier:	GPL-2.0

obj-y	+= mt7622_rfb.o

obj-$(CONFIG_MT7622_BOOTMENU_SNOR) += bootmenu_snor.o
obj-$(CONFIG_MT7622_BOOTMENU_SNAND) += bootmenu_snand.o
obj-$(CONFIG_MT7622_BOOTMENU_EMMC) += bootmenu_emmc.o
obj-$(CONFIG_MT7622_BOOTMENU_SD) += bootmenu_sd.o
