#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=10
STOP=98

boot() {
	[ -f /proc/mounts ] || /sbin/mount_root
	[ -f /proc/jffs2_bbc ] && echo "S" > /proc/jffs2_bbc
	[ -f /proc/net/vlan/config ] && vconfig set_name_type DEV_PLUS_VID_NO_PAD

	mkdir -p /var/run
	mkdir -p /var/log
	mkdir -p /var/lock
	mkdir -p /var/state
	mkdir -p /var/tmp
	mkdir -p /tmp/.uci
	chmod 0700 /tmp/.uci
	touch /var/log/wtmp
	touch /var/log/lastlog
	touch /tmp/resolv.conf.auto
	ln -sf /tmp/resolv.conf.auto /tmp/resolv.conf
	grep -q debugfs /proc/filesystems && /bin/mount -o noatime -t debugfs debugfs /sys/kernel/debug
    [ "$FAILSAFE" = "true" ] && touch /tmp/.failsafe

	/sbin/kmodloader

	# SpaceX: Attach and mount shared ubi filesystems
    /usr/sbin/ubiattach -p /dev/mtd11 -O 2048
	mount -a

	# TESTONLY: Enable persistent overlay.
	if [[ "$(cat /etc/overlay)" == "all" ]]; then
		enable_overlay
	fi

	# SpaceX: Record manufactured version to tmp file
	dd if=/dev/mtd5 bs=2048 skip=513 count=1 2>/dev/null | strings | head -c 256 > /tmp/manufactured_version

	# SpaceX: Run wifi_control early init, to create WifiState and Dat files before the wifi and
	# network subsystems are brought up
	wifi_control --early_init 2>&1 | head -c 100000 > /tmp/early_init.log

	################ SpaceX: Set iptables rules ################
	/sbin/setup_iptables.sh
	
	# temporary hack until configd exists
	/sbin/reload_config

	/sbin/configure_ephy.sh &
}
